☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/ansible/Taskfile.yml b/.config/taskfiles/ansible/Taskfile.yml
--- a/.config/taskfiles/ansible/Taskfile.yml
+++ b/.config/taskfiles/ansible/Taskfile.yml
@@ -231,6 +231,13 @@ tasks:
         vars:
           INSTALL_OPTIONS: --no-dev
     cmds:
+      - git reset --hard HEAD
+      - |
+        if ! git pull origin master; then
+          git config url."https://gitlab.com/".insteadOf git@gitlab.com:
+          git config url."https://github.com/".insteadOf git@github.com:
+          git pull origin master || true
+        fi
       - task: quickstart:environment
       - task: quickstart:map
       - task: quickstart:demo
@@ -265,7 +272,12 @@ tasks:
         3. It is stored in `~/.VAULT_PASSWORD` so you can easily spot it if something
         goes wrong.
     env:
+      ANSIBLE_CALLBACKS_ENABLED: 'junit, ansible.posix.profile_tasks, ansible.posix.timer, sentry'
+      ANSIBLE_STDOUT_CALLBACK: community.general.yaml
       ANSIBLE_VAULT_PASSWORD_FILE: ~/.VAULT_PASSWORD
+      JUNIT_FAIL_ON_CHANGE: true
+      JUNIT_HIDE_TASK_ARGUMENTS: true
+      JUNIT_OUTPUT_DIR: .results/junit
       QUICKSTART_PLAYBOOK_MATCH: |
         # Playbook Matching Inventory File Name
 
@@ -331,17 +343,28 @@ tasks:
                 export MOLECULE_GROUP="qubes"
               else
                 .config/log info 'Assuming machine to be macOS/Linux'
-                export MOLECULE_GROUP="nix"
+                export MOLECULE_GROUP="standard"
               fi
             fi
           fi
+          if [ -f local/requirements.txt ]; then
+            pip3 install -r local/requirements.txt
+          else
+            .config/log warn 'The `local/requirements.txt` file is missing'
+          fi
           if [ -f "playbooks/${INVENTORY_SLUG}.yml" ]; then
             PLAY_TMP="$(mktemp)" && echo "$QUICKSTART_PLAYBOOK_MATCH" > "$PLAY_TMP" && .config/log md "$PLAY_TMP"
-            {{.PYTHON_HANDLE}}ansible-playbook -i {{.INVENTORY}} "playbooks/${INVENTORY_SLUG}.yml"
+            {{.PYTHON_HANDLE}}ansible-playbook --skip-tags "dotfiles,mas" -vvv -i {{.INVENTORY}} "playbooks/${INVENTORY_SLUG}.yml" || EXIT_CODE="$?"
           else
             .config/log info 'Using the `main.yml` playbook because there is no playbook located in `'"playbooks/${INVENTORY_SLUG}.yml"'`'
-            {{.PYTHON_HANDLE}}ansible-playbook -i {{.INVENTORY}} main.yml
+            {{.PYTHON_HANDLE}}ansible-playbook --skip-tags "dotfiles,mas" -vvv -i {{.INVENTORY}} main.yml || EXIT_CODE="$?"
           fi
+          #if [ -n "$EXIT_CODE" ]; then
+          #  .config/log error 'There was an error while running the playbook.'
+          #  .config/log warn 'Ensure there are no secrets in plain text (if you choose to upload the logs so our developers can fix this issue).'
+          #  .config/log confirm 'Upload the playbook log so the developers can debug?'
+          #  # sentry-cli
+          #fi
         ignore_error: true
       - sleep 5
       - .config/log info 'Ensuring the temporary vault password file is forcibly removed'
diff --git a/.config/taskfiles/git/Taskfile.yml b/.config/taskfiles/git/Taskfile.yml
--- a/.config/taskfiles/git/Taskfile.yml
+++ b/.config/taskfiles/git/Taskfile.yml
@@ -70,14 +70,14 @@ tasks:
       - git init
       - git remote add origin "{{.GITLAB_REPO}}"
       - git add --all
-      - git commit --quiet -m "🧐 refactor(submodule): Adding folder/project to its own git repository."
+      - git commit --quiet -m "🧐 refactor(submodule) Adding folder/project to its own git repository."
       - git push --quiet -u --no-progress origin master
       - cd .. && rm -rf {{.BASENAME}}
       - cd .. && git add {{.BASENAME}}
-      - cd .. && git commit --quiet -m "🧐 refactor(submodule): Removing folder which will now be a submodule."
+      - git commit --quiet -m "🧐 refactor(submodule) Removing folder which will now be a submodule."
       - cd .. && git submodule add -b master "{{.GITLAB_REPO}}" {{.BASENAME}}
       - cd .. && git add {{.BASENAME}}
-      - cd .. && git commit --quiet -m "🧐 refactor(submodule): Adding new submodule which was previously a directory."
+      - cd .. && git commit --quiet -m "🧐 refactor(submodule) Adding new submodule which was previously a directory."
       - cd .. && git push --quiet -u --no-progress origin HEAD
     preconditions:
       - sh: '[[ ! $(git rev-parse --git-dir) =~ ".git/modules" ]]'
@@ -86,6 +86,17 @@ tasks:
   convert:folder:subrepo:
     deps:
       - :install:software:subrepo
+    summary: |
+      # Convert Folder to Sub-repo
+
+      This task will work if you have Taskfiles set up in a sub-directory of a project
+      that is already a git repository. Instead of using sub-modules, this method makes
+      the main repository's structure look as if no sub-module wizardry is going on.
+
+      To use this task, go into a sub-directory that you want to make a git subrepo and
+      then run `task git:convert:folder:subrepo` while making sure that the
+      `FULLY_AUTOMATED_TASKS` variables is set equal to `true`. There may be other
+      tokens required for accessing the APIs of GitHub, GitLab, etc.
     vars:
       BASENAME:
         sh: basename "$PWD"
@@ -97,20 +108,38 @@ tasks:
       success: Converted `{{.BASENAME}}` into a sub-repo
     cmds:
       - rm -rf .git
+      - git config url."git@gitlab.com:".insteadOf "https://gitlab.com/"
+      - git config url."git@github.com:".insteadOf "https://github.com/"
+      - task: commit:automated
       - |
         ROLE_DIR="$PWD"
         while ! test -d .git; do cd ..; done
-        git remote add {{.BASENAME}} {{.GITLAB_REPO}}
+        if ! git remote get-url {{.BASENAME}} &> /dev/null; then
+          git remote add {{.BASENAME}} {{.GITLAB_REPO}}
+        fi
         RELATIVE_DIR="$(echo $ROLE_DIR | sed 's@'"$PWD"'/@@')"
-        HUSKY=0 git subrepo clone {{.BASENAME}} "$RELATIVE_DIR" -b master
+        task git:commit:automated
+        HUSKY=0 git subrepo init "$RELATIVE_DIR" -r {{.BASENAME}} -b master
+    status:
+      - '[ "$FULLY_AUTOMATED_TASKS" != "true" ]'
 
   filter:
+    deps:
+      - :install:software:bfg
+    desc: Remove large unnecessary and large files from the repository
+    summary: |
+      # Clean Up Git Repository
+
+      This task will remove files that may have been committed by accident like node_modules.
+      It will also use [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to remove all files
+      that are over 50MB.
     log:
       error: Error filtering git history
       start: Filtering unnecessary items from git history
       success: Successfully filtered unnecessary items from git history
     cmds:
       - git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch -r **/node_modules/' --prune-empty -- --all
+      - bfg --strip-blobs-bigger-than 50M
 
   push:all:
     deps:
