☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/ansible/Taskfile-playbook.yml b/.config/taskfiles/ansible/Taskfile-playbook.yml
--- a/.config/taskfiles/ansible/Taskfile-playbook.yml
+++ b/.config/taskfiles/ansible/Taskfile-playbook.yml
@@ -2,6 +2,12 @@
 version: '3'
 
 tasks:
+  collections:download:
+    cmds:
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        ansible-galaxy collection download -r requirements.yml
+
   docs:
     deps:
       - docs:roles
@@ -106,7 +112,6 @@ tasks:
             fi
             LINK="$(echo $COMMENT | sed 's/ - .*//')"
             URL_LINK="$(echo "$LINK" | sed 's/@tui //' | sed 's/@service //' | sed 's/@binary //' | sed 's/@cli //' | sed 's/@application //' | sed 's/@menubar //' | sed 's/@webapp //' | sed 's/^\[\([^)]*\)\](\([^)]*\)).*$/\[\1\](\2)/' | sed 's/ $//' | sed 's/\/$//')"
-            echo "$URL_LINK"
             if [[ "$LINK" == *"[GitHub](NO_GITHUB_REPOSITORY_LINK)"* ]] || [[ "$LINK" != *"https://github.com"* ]]; then
               GITHUB_SHIELD="*N/A*"
             else
@@ -186,7 +191,7 @@ tasks:
             if test -L "$ITEM" || ! test -e "$ITEM"; then
               rm -f "$ITEM"
               ln -s "./environments/{{.CLI_ARGS}}/$ITEM" "$ITEM"
-              .config/log success "Successfully symlinked `$ITEM` from ./environments/{{.CLI_ARGS}}/$ITEM"
+              .config/log success "Successfully symlinked "'`'"$ITEM"'`'" from ./environments/{{.CLI_ARGS}}/$ITEM"
             else
               .config/log warn "$ITEM exists in the root and was not a symlink so it was skipped to prevent possible data loss"
             fi
@@ -194,9 +199,10 @@ tasks:
         {{else}}
           exit 69
         {{end}}
+      - .config/log finish 'Success `environment:cli`'
 
   environment:prompt:
-    vars:
+    env:
       MARKDOWN: |
         # Symlink Environment
 
@@ -209,30 +215,24 @@ tasks:
         symlink all of the items in the environments folder to the root as long as there
         is not anything except a symlink to the target location (i.e. it will overwrite
         symlinks but not files).
+
     cmds:
-      - task: :log:markdown
-        vars:
-          MARKDOWN: '{{.MARKDOWN}}'
+      - TMP="$(mktemp)" && echo "$MARKDOWN" > "$TMP" && .config/log md "$TMP"
       - task: environment:prompt:continue
 
   environment:prompt:continue:
     interactive: true
     deps:
+      - :install:software:gum
       - :install:software:jq
-    vars:
-      ENVIRONMENT_OPTIONS:
-        sh: find ./environments -maxdepth 1 -mindepth 1 | sed 's/\.\/environments\///' | jq -R '[.]' | jq -s -c 'add'
-    prompt:
-      type: select
-      message: Which environment would you like to use?
-      options: '{{.ENVIRONMENT_OPTIONS}}'
-      answer:
-        cmds:
-          - task: environment:cli
-            vars:
-              CLI_ARGS: '{{.ANSWER}}'
+    cmds:
+      - |
+        ENVIRONMENT_OPTIONS="$(find ./environments -maxdepth 1 -mindepth 1 | sed 's/\.\/environments\///' | jq -R '[.]' | jq -s -c -r 'add | join(" ")')"
+        .config/log prompt 'Select an environment from the `environments/` folder to symlink to'
+        ENV_OPTION="$(gum choose $(echo $ENVIRONMENT_OPTIONS))"
+        task ansible:playbook:environment:cli -- "$ENV_OPTION"
 
-  find-missing:
+  find-missing:files:
     desc: Find roles that are missing files
     hide: '{{ne (print .REPOSITORY_TYPE "-" .REPOSITORY_SUBTYPE) "ansible-playbook"}}'
     summary: |
@@ -258,6 +258,35 @@ tasks:
     preconditions:
       - sh: test -d roles
         msg: The `roles/` folder is missing. Is the project set up right?
+
+  find-missing:roles:
+    summary: |
+      # Find roles that are not in main.yml
+
+      This task will collect all the role paths in the `roles/` folder and return a list
+      of roles that are not present in the `main.yml` file.
+
+      If you want to scan something other than `main.yml`, you can pass the file in as a
+      CLI argument like so:
+
+      **Example scanning file other than `main.yml`:**
+      `task ansible:playbook:find-missing:roles -- playbooks/qubes.yml`
+    cmds:
+      - |
+        TMP="$(mktemp)"
+        RESULTS="$(mktemp)"
+        while read ROLE; do
+          ROLE_TITLE="$(echo "$ROLE" | sed 's/^.\///')"
+          if ! grep "$ROLE_TITLE" '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}main.yml{{end}}' > /dev/null; then
+            echo "$ROLE_TITLE" >> "$RESULTS"
+          fi
+        done< <(find ./roles -maxdepth 2 -mindepth 2)
+        if grep ".*" "$RESULTS"; then
+          .config/log info 'The roles missing from `{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}main.yml{{end}}` are:'
+          cat "$RESULTS"
+        else
+          .config/log info 'All of the roles are included in `{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}main.yml{{end}}`'
+        fi
 
   remotes:
     deps:
@@ -308,21 +337,40 @@ tasks:
         env:
           INSTALL_OPTIONS: --no-dev
       - :symlink:playbook
+    vars:
+      PLAYBOOK_MAIN:
+        sh: |
+          if [ -n "$PLAYBOOK_MAIN" ]; then
+            echo "$PLAYBOOK_MAIN"
+          else
+            echo "main.yml"
+          fi
     log:
       error: Error encounted while running `ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml`
       start: Running `ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml`
       success: Successfully ran `ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml`
     cmds:
-      - ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        if [ -z "$ANSIBLE_VAULT_PASSWORD" ]; then
+          .config/log info 'The `ANSIBLE_VAULT_PASSWORD` environment variable is not set so you will be prompted for the password'
+          ansible-playbook -i {{.CLI_ARGS}} --ask-vault-pass "{{.PLAYBOOK_MAIN}}"
+        else
+          echo "$ANSIBLE_VAULT_PASSWORD" > "$HOME/.VAULT_PASSWORD"
+          export ANSIBLE_VAULT_PASSWORD_FILE="$HOME/.VAULT_PASSWORD"
+          .config/log info 'Bypassing Ansible Vault password prompt since the `ANSIBLE_VAULT_PASSWORD` environment variable is set'
+          ansible-playbook -i {{.CLI_ARGS}} "{{.PLAYBOOK_MAIN}}"
+        fi
 
   run:prompt:
+    summary: '{{.MARKDOWN}}'
     vars:
       MARKDOWN: |
         # Run the Playbook
 
         These set of prompts will run the `main.yml` playbook after you specify:
 
-        1. The "environment"
+        (1) The "environment"
 
         The environment is a collection of folders that should, at the very minimum,
         include "files", "group_vars", "host_vars", and "inventories". Each folder in
@@ -330,35 +378,72 @@ tasks:
         environments, you can seperate different sets of variables/files or even seperate
         your private variables out into a sub-module.
 
-        2. An inventory file
+        (2) An inventory file
 
         The Ansible inventory stored in the "inventories" folder. This will generally be
         a YML file with host connection information that also correlates the inventory with
         the proper host_vars and group_vars. It is assumed that your sudo username and
         password are encrypted inside the inventory (via "ansible-vault").
+      PLAYBOOK_DESCRIPTIONS: |
+        # Playbook Descriptions
+
+        Playbooks are where you store your main logic in Ansible. The `main.yml` file in the
+        root of the repository is a generic one-size-fits-all approach. You could theoretically
+        store all your logic in one playbook for multiple scenarios with conditional logic but
+        it might be easier to create seperate playbooks in some cases. The `main.yml` should work
+        in most scenarios and is a great starting point.
+
+        ## Alternate Playbook Descriptions
+
+        Alternate playbooks are stored in the `playbooks/` directory. They are described below.
+
+        *If you want their description to show up in this message, you will have to edit the appropriate
+        field in `package.json`.*
+
+
+    env:
+      MARKDOWN: '{{.MARKDOWN}}'
     cmds:
-      - task: environment
-      - task: :log:markdown
-        vars:
-          MARKDOWN: '{{.MARKDOWN}}'
+      - |
+        MD_TMP="$(mktemp)"
+        echo "$MARKDOWN" > "$MD_TMP"
+        .config/log md "$MD_TMP"
       - task: run:prompt:continue
 
   run:prompt:continue:
     interactive: true
     deps:
       - :install:software:jq
-    vars:
-      INVENTORY_OPTIONS:
-        sh: find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c 'add'
-    prompt:
-      type: select
-      message: Which inventory would you like to use?
-      options: '{{.INVENTORY_OPTIONS}}'
-      answer:
-        cmds:
-          - task: run:cli
-            vars:
-              CLI_ARGS: '{{.ANSWER}}'
+    cmds:
+      - task: environment
+      - echo "\"inventories"$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"inventories")')"\""
+      - |
+        INVENTORY_OPTIONS_LENGTH="$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | length')"
+        if [[ "$INVENTORY_OPTIONS_LENGTH" == '0' ]]; then
+          .config/log error 'There are no inventory files present in the `inventories/` folder' && exit 1
+        else
+          INVENTORY_OPTIONS="$(echo "\""$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"")')"\"")"
+          .config/log prompt 'Which inventory would you like to use?'
+          CHOSEN_INVENTORY="$(.config/log choose $INVENTORY_OPTIONS)"
+          export PLAYBOOK_MAIN="main.yml"
+          if ! gum confirm "Would you like to use the main.yml playbook?"; then
+            PLAYBOOKS_OPTIONS="$(echo "\"playbooks"$(find ./playbooks/ -mindepth 1 -maxdepth 1 -name "*.yml" | sed 's/\.\/playbooks\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"playbooks")')"\"")"
+            PLAYBOOK_DESCS_TMP="$(mktemp)" && echo "$PLAYBOOK_DESCRIPTIONS" > "$PLAYBOOK_DESCS_TMP"
+            TMP_LIST="$(mktemp)"
+            find ./playbooks/ -mindepth 1 -maxdepth 1 -name "*.yml" | sed 's/\.\/playbooks\///' | jq -R '[.]' | jq -s -c -r 'add' >> "$TMP_LIST"
+            echo "* **main.yml:** A generic playbook that attempts to install everything" >> "$PLAYBOOK_DESCS_TMP"
+            jq -c -r '.[]' "$TMP_LIST" | while read SLUG; do
+              PLAYBOOK_DESC="$(jq -r '.blueprint.fileDescriptions[$file]' package.json)"
+              if [ "$PLAYBOOK_DESC" != 'null' ]; then
+                echo "* **playbooks/${SLUG}.yml:** $PLAYBOOK_DESC" >> "$PLAYBOOK_DESCS_TMP"
+              fi
+            done
+            .config/log md "$PLAYBOOK_DESCS_TMP"
+            .config/log prompt 'Select the playbook you would like to provision with.'
+            export PLAYBOOK_MAIN="$(.config/log choose $PLAYBOOKS_OPTIONS)"
+          fi
+          task ansible:playbook:run:cli -- "$CHOSEN_INVENTORY"
+        fi
 
   subrepo:init:
     deps:
